/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formlaporan;

import Class.ClassDatabase;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author pc
 */
public class laporanlabarugi_1 extends javax.swing.JFrame {
private String sql;
private Connection con;
    public static ResultSet rs;
static java.sql.Statement stat;
   private String tgl;
    /**
    /**
     * Creates new form laporanlabarugi
     */
    public laporanlabarugi_1() {
        
        initComponents();
        total_harga();
        totalharga();
        hasil();
        a1();
        a2();
        a3();
        a4();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kredit = new javax.swing.JTextField();
        debit = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        laba = new javax.swing.JTextField();
        hasil1 = new javax.swing.JTextField();
        prive = new javax.swing.JTextField();
        penambah = new javax.swing.JTextField();
        akhir = new javax.swing.JTextField();
        modal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        B1 = new javax.swing.JTextField();
        B2 = new javax.swing.JTextField();
        B3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        B9 = new javax.swing.JTextField();
        medel = new javax.swing.JTextField();
        preve = new javax.swing.JTextField();
        penembah = new javax.swing.JTextField();
        k3 = new javax.swing.JTextField();
        k2 = new javax.swing.JTextField();
        k1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kredit.setText("0");
        jPanel1.add(kredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 90, 0));

        debit.setText("0");
        jPanel1.add(debit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 80, 0));
        jPanel1.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 130, 0));

        jButton1.setText("CETAK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LAPORAN LAPORAN PERUBAHAN MODAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 410, -1));
        jPanel1.add(laba, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, 0));

        hasil1.setText("0");
        jPanel1.add(hasil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 160, 30));

        prive.setText("0");
        jPanel1.add(prive, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 160, 30));

        penambah.setText("0");
        penambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penambahActionPerformed(evt);
            }
        });
        jPanel1.add(penambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 160, 30));

        akhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akhirActionPerformed(evt);
            }
        });
        jPanel1.add(akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 160, 30));

        modal.setText("0");
        jPanel1.add(modal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 160, 30));

        jButton2.setText("proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        B1.setText("MODAL AWAL");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 90, -1));

        B2.setText("PRIVE");
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 80, -1));

        B3.setText("B0019");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 40, -1));

        jButton3.setText("proses");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jButton4.setText("proses");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jButton5.setText("PROSES");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        jButton7.setText("EXIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        B9.setText("PENAMBAHAN MODAL");
        jPanel1.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 130, -1));

        medel.setText("J001");
        jPanel1.add(medel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 110, 0));

        preve.setText("J008");
        jPanel1.add(preve, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 110, 0));

        penembah.setText("J0010");
        jPanel1.add(penembah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 110, 0));

        k3.setText("0");
        k3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k3ActionPerformed(evt);
            }
        });
        jPanel1.add(k3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, 0));

        k2.setText("0");
        jPanel1.add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 0));

        k1.setText("0");
        jPanel1.add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
         
          String tgls3= k1.getText();
           String tgls4= hasil1.getText();
             String tgls5= k2.getText();
           String tgls6= k3.getText();
 String tgls7= akhir.getText();
 
           System.out.println(tgls3);    
            System.out.println(tgls4);
            System.out.println(tgls5);
             System.out.println(tgls6); 
             System.out.println(tgls7); 
            
            String reportName = ClassDatabase.PathReport + "perubahanlap.jasper";
            HashMap parameter = new HashMap();
            File reportFile = new File(reportName);
        parameter.put("modal",tgls3);
             parameter.put("hasil",tgls4);
             parameter.put("prive",tgls5);
              parameter.put("penambah",tgls6);
                parameter.put("akhir",tgls7);
        
            JasperReport jReport = (JasperReport)JRLoader.loadObject(reportFile.getPath());
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, ClassDatabase.getkoneksi());
                                JasperViewer.viewReport(jPrint,false);
  
            } catch (Exception ex) {
                System.out.println(ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try {
         dbconnect();
             sql =  "select sum(debit) from jurnal where namaperkiraan= ?";
            PreparedStatement ps = con.prepareStatement(sql);
         ps.setString(1,B1.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                modal.setText(rs.getString(1));
                prive.setText("0");
            }
        } catch (SQLException se) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
         dbconnect();
             sql =  "select sum(debit) from jurnal where namaperkiraan= ?";
            PreparedStatement ps = con.prepareStatement(sql);
         ps.setString(1,B3.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                penambah.setText(rs.getString(1));
                prive.setText("0");
            }
        } catch (SQLException se) {
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
         dbconnect();
             sql =  "select sum(debit) from jurnal where namaperkiraan= ?";
            PreparedStatement ps = con.prepareStatement(sql);
         ps.setString(1,B2.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                prive.setText(rs.getString(1));
                prive.setText("0");
            }
        } catch (SQLException se) {
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void penambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penambahActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int jumlah_beli, stok_awal, jum_stok,harga_beli, subtotal, total,A,B;
        String sub_total, stok_akhir;

        harga_beli = Integer.parseInt(modal.getText());
        jumlah_beli = Integer.parseInt(hasil1.getText());
        A = Integer.parseInt(prive.getText());
        B= Integer.parseInt(penambah.getText());

        

        subtotal = harga_beli + jumlah_beli - A + B;
        sub_total = String.valueOf(subtotal);
        akhir.setText(sub_total); 
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void akhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akhirActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_akhirActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void k3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanlabarugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanlabarugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanlabarugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanlabarugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanlabarugi_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B2;
    private javax.swing.JTextField B3;
    private javax.swing.JTextField B9;
    private javax.swing.JTextField akhir;
    private javax.swing.JTextField debit;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField hasil1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField k1;
    private javax.swing.JTextField k2;
    private javax.swing.JTextField k3;
    private javax.swing.JTextField kredit;
    private javax.swing.JTextField laba;
    private javax.swing.JTextField medel;
    private javax.swing.JTextField modal;
    private javax.swing.JTextField penambah;
    private javax.swing.JTextField penembah;
    private javax.swing.JTextField preve;
    private javax.swing.JTextField prive;
    // End of variables declaration//GEN-END:variables
private void dbconnect() {
         try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbc");
            con=DriverManager.getConnection("jdbc:odbc:dstoko");
            stat=con.createStatement();
        }catch (Exception ce) {JOptionPane.showMessageDialog(null,"Koneksi gagal..");
        }
    }
    private void total_harga(){
     try {
         dbconnect();
             sql = "select sum(debit) from jurnal ";
            PreparedStatement ps = con.prepareStatement(sql);
         
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                debit.setText(rs.getString(1));
            }
        } catch (SQLException se) {
        }
    }
      private void totalharga(){
     try {
         dbconnect();
             sql = "select sum(kredit) from jurnal ";
            PreparedStatement ps = con.prepareStatement(sql);
         
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                kredit.setText(rs.getString(1));
            }
        } catch (SQLException se) {
        }
    }
      
      private void hasil(){
           
   
  int totalharga,totalbayar,subtotal,subtotal1;
        String sub_total, stok_akhir,sub_total1,subtotalt;

        totalharga = Integer.parseInt(debit.getText());
        totalbayar = Integer.parseInt(kredit.getText());
      
        sub_total = String.valueOf(totalharga);
         subtotalt = String.valueOf(totalbayar);
        hasil1.setText(sub_total);
        hasil1.setText(subtotalt);
         
       subtotal1 = totalbayar-totalharga;
        sub_total1 = String.valueOf(subtotal1);
     
       
            if (totalbayar<totalharga){
        
                 hasil1.setText(sub_total);
                 laba.setText(" LABA ");
              
        }
        else {
                  hasil1.setText(subtotalt);
                  laba.setText(" RUGI");
              
        
}
      }
 private void a1(){
    String gol,a,b;
     try {
         dbconnect();
             sql =  "select sum(debit) from jurnal where kdperkiraan= ?";
            PreparedStatement ps = con.prepareStatement(sql);
         ps.setString(1,medel.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
               
                k1.setText(rs.getString(1));
    
         
            }

              
            
  
        } catch (SQLException se) {
              
        }  
 }
 private void a2(){
try {
         dbconnect();
             sql =  "select sum(debit) from jurnal where kdperkiraan= ?";
            PreparedStatement ps = con.prepareStatement(sql);
         ps.setString(1,preve.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                k2.setText(rs.getString(1));
                
            }
          
        } catch (SQLException se) {
        }  
 }
 private void a3(){
  try {
         dbconnect();
             sql =  "select sum(debit) from jurnal where kdperkiraan= ?";
            PreparedStatement ps = con.prepareStatement(sql);
         ps.setString(1,penembah.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                k3.setText(rs.getString(1));
                
            }
             k3.setText("0");
        } catch (SQLException se) {
        } 
 }
 private void a4(){
     int jumlah_beli, stok_awal, jum_stok,harga_beli, subtotal, total,A,B;
        String sub_total, stok_akhir;

        harga_beli = Integer.parseInt(k1.getText());
        jumlah_beli = Integer.parseInt(hasil1.getText());
        A = Integer.parseInt(k2.getText());
        B= Integer.parseInt(k3.getText());

        

        subtotal = harga_beli + jumlah_beli - A + B;
        sub_total = String.valueOf(subtotal);
        akhir.setText(sub_total); 
 }
 

}
