/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formlaporan;

import Class.ClassDatabase;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author pc
 */
public class laporanlabarugi extends javax.swing.JFrame {
private String sql;
private Connection con;
    public static ResultSet rs;
static java.sql.Statement stat;
   private String tgl;
    /**
    /**
     * Creates new form laporanlabarugi
     */
    public laporanlabarugi() {
        
        initComponents();
   total_harga();
   totalharga();
        hasil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        kredit = new javax.swing.JTextField();
        debit = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        laba = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        heheh = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jMonthChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, 40));
        jPanel1.add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, 40));

        kredit.setText("0");
        jPanel1.add(kredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 90, 0));

        debit.setText("0");
        jPanel1.add(debit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 80, 0));
        jPanel1.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 130, 0));

        jButton1.setText("CETAK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LAPORAN LABA RUGI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 260, -1));
        jPanel1.add(laba, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, 0));

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, 30));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 100, 40));
        jPanel1.add(heheh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, 40));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 80, 30));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
         
          String tgls4= jTextField1.getText();
           String tgls3= jTextField3.getText();
             String tgls5= jTextField4.getText();
           String tgls6= heheh.getText();
           
           System.out.println(tgls3);    
            System.out.println(tgls4);
            System.out.println(tgls5);
             System.out.println(tgls6); 
            
            String reportName = ClassDatabase.PathReport + "labarugilap.jasper";
            HashMap parameter = new HashMap();
            File reportFile = new File(reportName);
        
             parameter.put("jdebit",tgls3);
             parameter.put("jkredit",tgls5);
               parameter.put("hasil",tgls4);
              parameter.put("ket",tgls6);
            JasperReport jReport = (JasperReport)JRLoader.loadObject(reportFile.getPath());
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, ClassDatabase.getkoneksi());
                                JasperViewer.viewReport(jPrint,false);
  
            } catch (Exception ex) {
                System.out.println(ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanlabarugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanlabarugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanlabarugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanlabarugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanlabarugi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField debit;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField heheh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JTextField kredit;
    private javax.swing.JTextField laba;
    // End of variables declaration//GEN-END:variables
private void dbconnect() {
         try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbc");
            con=DriverManager.getConnection("jdbc:odbc:dstoko");
            stat=con.createStatement();
        }catch (Exception ce) {JOptionPane.showMessageDialog(null,"Koneksi gagal..");
        }
    }
    private void total_harga(){
     try {
         dbconnect();
             sql = "select sum(debit) from jurnal ";
            PreparedStatement ps = con.prepareStatement(sql);
         
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jTextField3.setText(rs.getString(1));
            }
        } catch (SQLException se) {
        }
    }
      private void totalharga(){
     try {
         dbconnect();
             sql = "select sum(kredit) from jurnal ";
            PreparedStatement ps = con.prepareStatement(sql);
         
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jTextField4.setText(rs.getString(1));
            }
        } catch (SQLException se) {
        }
    }
      
      private void hasil(){
           
   
  int totalharga,totalbayar,subtotal,subtotal1;
        String sub_total, stok_akhir,sub_total1,subtotalt;

        totalharga = Integer.parseInt(jTextField3.getText());
        totalbayar = Integer.parseInt(jTextField4.getText());
   
      
         
       subtotal1 = totalharga-totalbayar;
        sub_total1 = String.valueOf(subtotal1);
     jTextField1.setText(sub_total1);
       
            if (totalbayar<totalharga){
        
                 jTextField1.setText(sub_total1);
                 heheh.setText(" LABA ");
              
        }
        else if (totalbayar>totalharga){
                  jTextField1.setText(sub_total1);
                  heheh.setText(" RUGI");
              
        
}
               
      
      }
}