/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;



import static form.perkiraan.stat;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class jurnal extends javax.swing.JFrame {
  private String sql;
private Connection con;
    public static ResultSet rs;
static java.sql.Statement stat;
    /**
     * Creates new form jurnal
     */
    public jurnal() {
        initComponents();
        cikin();
        tampil_pelanggan();
     new dbconnect().dbconnecte("kdtransaksi", "jurnal", 4,"F");
        kdtransaksi.setText(dbconnect.penomoran);
                tampil_pelanggan();
    }
    public static Date getTanggalFromTable(JTable table, int kolom){
        JTable tabel = table;
        String str_tgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(), kolom));
        Date tanggal = null;
        try {
            tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(str_tgl);
        } catch (ParseException ex) {
            Logger.getLogger(TableDate.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tanggal;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kdtransaksi = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ket = new javax.swing.JTextField();
        vkredit = new javax.swing.JTextField();
        vjml = new javax.swing.JTextField();
        vdebit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        vjenis = new javax.swing.JComboBox();
        kper = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 840, 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TOKO KOPI SEDUH");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("KREDIT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 60, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("INPUT DATA JURNAL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("TANGGAL TRANSAKSI");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "TGL ", "KD JURNAL", "KET", "NAMA", "JENIS ", "JUMLAH", "DEBIT", "KREDIT"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 850, 90));
        jPanel2.add(kdtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 220, 30));

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 110, 30));
        jPanel2.add(ket, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 220, 30));
        jPanel2.add(vkredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 140, 30));

        vjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vjmlActionPerformed(evt);
            }
        });
        jPanel2.add(vjml, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 220, 30));
        jPanel2.add(vdebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("JUMLAH");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("DEBIT");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("KODE JURNAL");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("KETERANGAN");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("NAMA PERKIRAAN");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("JENIS TRANSAKSI");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jButton5.setText("SIMPAN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 110, 30));

        jButton6.setText("EDIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 110, 30));

        jButton7.setText("HAPUS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 110, 30));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 220, 30));

        vjenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "===PILIH====", "DEBIT", "KREDIT" }));
        vjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vjenisActionPerformed(evt);
            }
        });
        jPanel2.add(vjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 110, 30));
        jPanel2.add(kper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 0, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 220, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vjenisActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_vjenisActionPerformed

    private void vjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vjmlActionPerformed
  String jenistrans;
        int jumlahtrans, debit, kredit=0;
        jenistrans=(String) vjenis.getSelectedItem();
        jumlahtrans=Integer.parseInt(vjml.getText());
        if (jenistrans=="DEBIT") {

            vdebit.setText(String.valueOf(jumlahtrans));
            vkredit.setText("0");
        }
        else if (jenistrans=="KREDIT"){

            vkredit.setText(String.valueOf(jumlahtrans));
            vdebit.setText("0");
        }
                  // TODO add your handling code here:
    }//GEN-LAST:event_vjmlActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int ok = JOptionPane.showConfirmDialog(null, "Anda Yakin Akan Menyimpan Data Ini ??? ","",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            if( ket.getText().isEmpty() || vjml.getText().isEmpty())
                   
                 
                 {
                JOptionPane.showMessageDialog(null, "Data Tidak Lengkap");
                
            }
            else
            {
         String tgl="";
         
            dbconnect();
              String pattern = "yyyy-MM-dd";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                tgl=String.valueOf(format.format(jDateChooser1.getDate()));
           
        try {
            sql ="insert into jurnal values('" +tgl+"','"
               +kdtransaksi.getText()+"','" 
                    +kper.getText()+"','" 
                    +ket.getText()+"','" 
                    +vjenis.getSelectedItem()+"','" 
                    +vjml.getText()+"','" 
                   +vdebit.getText()+"','" 
                    +vkredit.getText()+"')";
              stat.execute(sql);
              
            JOptionPane.showMessageDialog(null, "data disimpan");
            ket.setText("");
            vjml.setText("");
            vdebit.setText("");
            vkredit.setText("");
  tampil_pelanggan();
      new dbconnect().dbconnecte("kdtransaksi", "jurnal", 4,"F");
        kdtransaksi.setText(dbconnect.penomoran);        
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "data tidak disimpan");    
       
        
        }   
 
         
      
        }
            }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   String kode1 = kdtransaksi.getText();
   String tgl="";
        try {
             dbconnect();
                String pattern = "yyyy-MM-dd";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                tgl=String.valueOf(format.format(jDateChooser1.getDate()));
            String SQL = "update jurnal set tgltransaksi=?,kdperkiraan=?,ket=?,jenis=?,jumlah=?,debit=?, kredit=?"
                    + " where kdtransaksi='" + kode1 + "'";
            PreparedStatement PS = (PreparedStatement) con.prepareStatement(SQL);
            PS.setString(1, tgl);
            PS.setString(2,  kper.getText());
            PS.setString(3, ket.getText());
            
            PS.setString(4, vjenis.getSelectedItem().toString());
            PS.setString(5, vjml.getText());
            PS.setString(6, vdebit.getText());
            PS.setString(7, vkredit.getText());

            int data = PS.executeUpdate();
            if (data != 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            tampil_pelanggan();
                
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diubah");
            }
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(this, "Data gagal diubah");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try {
      dbconnect();
                PreparedStatement statement = con.prepareStatement("delete from jurnal where kdtransaksi=?");
                statement.setString(1, kdtransaksi.getText());
                statement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data berhasil dihapus...");
                     kdtransaksi.setEnabled(true);
                tampil_pelanggan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data gagal dihapus...");
        }              // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int row = jTable1.getSelectedRow();
   jDateChooser1.setDate(getTanggalFromTable(jTable1, 1));
kdtransaksi.setText(jTable1.getValueAt(row, 2).toString());
         ket.setText(jTable1.getValueAt(row, 3).toString());
          jComboBox1.setSelectedItem(jTable1.getValueAt(row, 4).toString());
          
         vjenis.setSelectedItem(jTable1.getValueAt(row, 5).toString());
          vjml.setText(jTable1.getValueAt(row, 5).toString());
          vdebit.setText(jTable1.getValueAt(row, 6).toString());
       vkredit.setText(jTable1.getValueAt(row, 7).toString());
        kdtransaksi.setEnabled(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
String amanda;
        try {
            Object tampil=jComboBox1.getSelectedItem();
            amanda=tampil.toString();
           dbconnect();
            sql="SELECT * FROM perkiraan WHERE namaperkiraan='"+amanda+"'";
            stat=con.createStatement();
            rs = stat.executeQuery(sql);
            while(rs.next()) {
                jComboBox1.setSelectedItem(rs.getString("namaperkiraan"));
                kper.setText(rs.getString("kdperkiraan"));
                 
            }
        } catch (Exception e) {
            
          
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jurnal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kdtransaksi;
    private javax.swing.JTextField ket;
    private javax.swing.JTextField kper;
    private javax.swing.JTextField vdebit;
    private javax.swing.JComboBox vjenis;
    private javax.swing.JTextField vjml;
    private javax.swing.JTextField vkredit;
    // End of variables declaration//GEN-END:variables
private void dbconnect() {
         try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbc");
            con=DriverManager.getConnection("jdbc:odbc:dstoko");
            stat=con.createStatement();
        }catch (Exception ce) {JOptionPane.showMessageDialog(null,"Koneksi gagal..");
        }
    }
private void cikin(){
        jComboBox1.removeAllItems();
        jComboBox1.addItem("PILIH");
        jComboBox1.setSelectedItem("PILIH");
        try {
            dbconnect();
            sql="SELECT * FROM perkiraan";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);

            while(rs.next())
            {
                jComboBox1.addItem(rs.getString("namaperkiraan"));
            }
            rs.close();
        } catch (Exception e) {
        }
    }
private void tampil_pelanggan()
    {
     DefaultTableModel tableModel=new DefaultTableModel();
        tableModel.addColumn("NOMOR");
        tableModel.addColumn("TGL");
        tableModel.addColumn("KD JURNAL");
        tableModel.addColumn("KET");
        tableModel.addColumn("KD PERKIRAAN");
        tableModel.addColumn("NAMA PERKIRAAN");
         tableModel.addColumn("JENIS");
          tableModel.addColumn("JUMLAH");
           tableModel.addColumn("DEBIT");
            tableModel.addColumn("KREDIT");
        
        int no=1;
        try{
           Class.forName("sun.jdbc.odbc.JdbcOdbc");
            con=DriverManager.getConnection("jdbc:odbc:dstoko");
            String sql="select * from  `perkiraan` perkiraan INNER JOIN `jurnal` jurnal ON perkiraan.`kdperkiraan` = jurnal.`kdperkiraan`";
            Statement stat=con.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                tableModel.addRow(new Object[]{(""+no++),
               rs.getString("tgltransaksi"),
               rs.getString("kdtransaksi"),
               rs.getString("ket"),
              
               rs.getString("namaperkiraan"),
               rs.getString("jenis"),
               rs.getString("jumlah"),
               rs.getString("debit"),
              
                rs.getString("kredit")});
            }
            jTable1.setModel(tableModel);
        }catch(Exception e){  
        }  
    }

    private static class TableDate {

        public TableDate() {
        }
    }
}

